<?php

use ThemeIntegration\ThemeModule\Block\ShoesList;

$blockObj = $block->getLayout()->createBlock(ShoesList::class);
$shoesData = $blockObj->getShoesList();

?>

<script>
    require(['jquery', 'carousel'], function($) {
        $('.product-carousel').owlCarousel({
            loop: true,
            responsiveClass: true,
            margin: 20,
            responsive: {
                0: {
                    items: 1
                },
                400: {
                    items: 2,
                    margin: 20
                },
                600: {
                    items: 3
                },
                800: {
                    items: 4
                },
                1100: {
                    items: 5
                },
                1350: {
                    items: 6
                }
            }
        });
    });
</script>

<section class="products-section">
    <div class="page-main">
        <div class="content-heading">
            <h2 class="title">Mens Shoes</h2>
        </div>
        <div class="block widget block-products-list grid">
            <div class="block-content">
                <div class="products-grid grid">
                    <ol class="product-items widget-product-grid owl-carousel owl-theme product-carousel">
                        <?php foreach ($shoesData as $shoe): ?>
                            <?php
                            $productImage = $blockObj->getProductImageUrl($shoe);
                            $productId = $blockObj->getProductId($shoe);
                            $simpleProducts = $blockObj->getSimpleProduct($productId);
                            $formKey = $blockObj->getFormKeyForWishlist();
                            ?>
                            <li class="product-item">
                                <div class="product-item-info">
                                    <a href="#" class="product-item-photo">
                                        <span 
                                        class="product-image-container product-image-container-1562" 
                                        style="width: 240px;"
                                        >
                                            <span class="product-image-wrapper" 
                                            style="padding-bottom: 125%;">
                                                <img class="product-image-photo config-product-image" 
                                                src="<?=/* @noEscape */ $productImage; ?>"
                                                data-product-id="<?=/* @noEscape */ $productId; ?>" 
                                                loading="lazy" 
                                                width="240" 
                                                height="300" 
                                                alt="Product image"
                                                >
                                            </span>
                                        </span>
                                    </a>
                                    <style>
                                        .product-image-container-1562 {
                                            width: 240px;
                                        }

                                        .product-image-container-1562 span.product-image-wrapper {
                                            padding-bottom: 125%;
                                        }
                                    </style>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a 
                                                title="Radiant Tee" 
                                                href="#" 
                                                class="product-item-link"><?=/* @noEscape */ $shoe['name']; ?>
                                            </a>
                                        </strong>
                                        <div class="price-box price-final_price" 
                                        data-role="priceBox" 
                                        data-product-id="<?=/* @noEscape */ $productId; ?>" 
                                        data-price-box="product-id-1562"
                                        >
                                            <span class="old-price">
                                                <span><?=/* @noEscape */ $shoe['price']; ?></span>
                                            </span>
                                            <span class="normal-price">
                                                <span class="price-container price-final_price tax weee">
                                                    <span id="old-price-1562-widget-product-grid" 
                                                    data-price-amount="22" 
                                                    data-price-type="finalPrice" 
                                                    class="price-wrapper"
                                                    >
                                                    <span class="price">₹522.00</span></span>
                                                </span>
                                            </span>
                                        </div>
                                        <div 
                                            class="swatch-opt-1562" 
                                            data-role="swatch-option-1562" 
                                            data-rendered="true"
                                        >
                                            <div class="swatch-attribute size" 
                                            data-attribute-code="size" 
                                            data-attribute-id="144"
                                            ></div>
                                            <div 
                                                class="swatch-attribute color" 
                                                data-attribute-code="color" 
                                                data-attribute-id="93"
                                            >
                                                <div aria-activedescendant="" 
                                                tabindex="0" 
                                                aria-invalid="false" 
                                                aria-required="true" 
                                                role="listbox" 
                                                aria-label="Color" 
                                                class="swatch-attribute-options clearfix"
                                                >
                                                    <?php foreach ($simpleProducts as $simpleProduct): ?>
                                                        <button class="swatch-option color" 
                                                        id="option-label-color-93-item-50" 
                                                        index="0" aria-checked="false" 
                                                        aria-describedby="option-label-color-93" 
                                                        tabindex="0" 
                                                        data-option-type="1" 
                                                        data-option-id="<?=/* @noEscape */ $simpleProduct['id']; ?>" 
                                                        data-option-label="Blue" 
                                                        aria-label="Blue" 
                                                        role="option" 
                                                        data-thumb-width="110" 
                                                        data-thumb-height="90" 
                                                        data-option-tooltip-value="#DD4A4A" 
                                                        style="background: 
                                                        <?=/* @noEscape */ $simpleProduct['color']; ?> 
                                                        no-repeat center; background-size: initial;"
                                                        
                                                        >
                                                    </button>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <div 
                                                    class="actions-primary" 
                                                    data-form-key="<?=/* @noEscape */ $formKey; ?>"
                                                >
                                                    <form 
                                                        name="addToCart" 
                                                        data-role="tocart-form" 
                                                        data-product-sku="WS12" 
                                                        action="" 
                                                        method="post"
                                                    >
                                                        <input 
                                                            type="hidden" 
                                                            name="product" 
                                                            value="<?=/* @noEscape */ $productId; ?>"
                                                        >
                                                        <input 
                                                        type="hidden" 
                                                        name="form-key" 
                                                        value="<?=/* @noEscape */ $formKey; ?>">
                                                        <input 
                                                            name=" uenc" 
                                                            value="Please select a product" 
                                                            style="display:none; color:red;"
                                                        >
                                                        <input 
                                                            name="form_key" 
                                                            type="hidden" 
                                                            value="njfb4cUiqt9DIdtW"
                                                        >
                                                        <button 
                                                            type="submit" 
                                                            title="Add to Cart" 
                                                            class="action tocart primary">
                                                            <span>Add to Cart</span>
                                                        </button>
                                                        <input 
                                                            class="swatch-input super-attribute-select" 
                                                            name="super_attribute[144]" 
                                                            type="text" value="" 
                                                            data-selector="super_attribute[144]" 
                                                            data-validate="{required: true}" 
                                                            aria-required="true" 
                                                            aria-invalid="false"
                                                        >
                                                        <input 
                                                            class="swatch-input super-attribute-select" 
                                                            name="super_attribute[93]" 
                                                            type="text" value="" 
                                                            data-selector="super_attribute[93]" 
                                                            data-validate="{required: true}" 
                                                            aria-required="true" 
                                                            aria-invalid="false"
                                                        >
                                                    </form>
                                                </div>
                                                <div class="actions-secondary" 
                                                data-role="add-to-links" 
                                                data-product-id="<?=/* @noEscape */ $productId; ?>" 
                                                data-form-key="<?=/* @noEscape */ $formKey; ?>">
                                                <a class="action towishlist" 
                                                    data-action="add-to-wishlist" 
                                                    title="Add to Wish List">
                                                    <span>Add to Wish List</span>
                                                </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>