<?php

use ThemeIntegration\ThemeModule\Block\CategoryList;

$blockobj = $block->getLayout()->createBlock(CategoryList::class);

$category = $blockobj->getCategoryCollection();


?>

<script>
    console.log('kerii')
    require(['jquery', 'carousel'], function($) {
        console.log('hellow')
        $('.top-category-slider-custom').owlCarousel({
            loop: true,
            dots: false,
            autoPlay: 2000,
            responsive: {
                0: {
                    autoWidth: true,
                    margin: 10
                },
                768: {
                    items: 4
                },
                800: {
                    items: 4
                },
                900: {
                    items: 5
                },
                1000: {
                    items: 6
                },
                1200: {
                    items: 7
                },
                1300: {
                    items: 8
                },
                1500: {
                    items: 9
                }
            }
        })
    });
</script>


<section class="top-category-section">
    <div class="page-main">
        <div class="content-heading">
            <h2 class="title">Top Categories</h2>
        </div>
        <ul class="owl-carousel owl-theme top-category-slider-custom">
            <?php foreach ($category as $singleCategory): ?>
                <li class="top-category-list">
                    <a href="#">
                        <figure 
                            class="top-category-image" 
                            style="background-image: url('<?=/* @noEscape */$singleCategory['image']; ?>');"
                        > 
                    </figure>
                        <h4><?=/* @noEscape */$singleCategory['name']; ?></h4>
                    </a>
                </li>
            <?php endforeach; ?>

        </ul>
    </div>
</section>