<div class="footer links">
    <h4>Quick Access</h4>
    <ul>
        <li class="nav item"><a href="#">Fashion </a></li>
        <li class="nav item"><a href="#">Shoes </a></li>
        <li class="nav item"><a href="#">Mobile Phones </a></li>
        <li class="nav item"><a href="#">Bags </a></li>
        <li class="nav item"><a href="#">Body care </a></li>
        <li class="nav item"><a href="#">Electronics </a></li>
        <li class="nav item"><a href="#">New Arrival </a></li>
    </ul>
</div>